# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BİTİRME.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import *
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1577, 858)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 10, 1581, 821))
        self.frame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(219, 223, 253);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(260, 50, 1280, 720))
        self.widget.setObjectName("widget")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(20, 120, 221, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.run = QtWidgets.QPushButton(self.frame)
        self.run.setGeometry(QtCore.QRect(90, 730, 89, 25))
        self.run.setObjectName("run")
        self.dosya_sec = QtWidgets.QPushButton(self.frame)
        self.dosya_sec.setGeometry(QtCore.QRect(20, 70, 111, 25))
        self.dosya_sec.setObjectName("dosya_sec")
        self.klasor_sec = QtWidgets.QPushButton(self.frame)
        self.klasor_sec.setGeometry(QtCore.QRect(138, 70, 101, 25))
        self.klasor_sec.setObjectName("klasor_sec")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        #self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "YoloV4-FB-416"))
        self.comboBox.setItemText(1, _translate("MainWindow", "YoloV4-CB-416"))
        self.comboBox.setItemText(2, _translate("MainWindow", "YoloV4-FB-512"))
        self.comboBox.setItemText(3, _translate("MainWindow", "YoloV4-CB-512"))
        self.comboBox.setItemText(4, _translate("MainWindow", "YoloV4-FB-640"))
        self.comboBox.setItemText(5, _translate("MainWindow", "YoloV4-CB-640"))
        self.comboBox.setItemText(6, _translate("MainWindow", "YoloV5-FB-416"))
        self.comboBox.setItemText(7, _translate("MainWindow", "YoloV5-CB-416"))
        self.comboBox.setItemText(8, _translate("MainWindow", "YoloV5-FB-512"))
        self.comboBox.setItemText(9, _translate("MainWindow", "YoloV5-CB-512"))
        self.comboBox.setItemText(10, _translate("MainWindow", "YoloV5-FB-640"))
        self.comboBox.setItemText(11, _translate("MainWindow", "YoloV5-CB-640"))
        self.comboBox.setItemText(12, _translate("MainWindow", "YOLOR-FB-416"))
        self.comboBox.setItemText(13, _translate("MainWindow", "YOLOR-CB-416"))
        self.comboBox.setItemText(14, _translate("MainWindow", "YOLOR-FB-512"))
        self.comboBox.setItemText(15, _translate("MainWindow", "YOLOR-CB-512"))
        self.comboBox.setItemText(16, _translate("MainWindow", "YOLOR-FB-640"))
        self.comboBox.setItemText(17, _translate("MainWindow", "YOLOR-CB-640"))
        self.run.setText(_translate("MainWindow", "Çalıştır"))
        self.dosya_sec.setText(_translate("MainWindow", "Dosya Seç"))
        self.klasor_sec.setText(_translate("MainWindow", "Klasör Seç"))
