# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BİTİRME.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import *
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1584, 810)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 1601, 921))
        self.frame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(219, 223, 253);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QLabel(self.frame)
        self.widget.setGeometry(QtCore.QRect(220, 20, 1351, 761))
        self.widget.setObjectName("widget")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(40, 470, 131, 31))
        self.comboBox.setObjectName("comboBox")

        for i in range(0, 36):
            self.comboBox.addItem("")

        self.dosya_sec = QtWidgets.QPushButton(self.frame)
        self.dosya_sec.setGeometry(QtCore.QRect(40, 310, 131, 31))
        self.dosya_sec.setObjectName("dosya_sec")
        self.klasor_sec = QtWidgets.QPushButton(self.frame)
        self.klasor_sec.setGeometry(QtCore.QRect(40, 390, 131, 31))
        self.klasor_sec.setObjectName("klasor_sec")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 40, 150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/output-onlinepngtools (7).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.durdur = QtWidgets.QPushButton(self.frame)
        self.durdur.setGeometry(QtCore.QRect(40, 540, 131, 31))
        self.durdur.setObjectName("durdur")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "YoloV4-FB-416"))
        self.comboBox.setItemText(1, _translate("MainWindow", "YoloV4-CB-416"))
        self.comboBox.setItemText(2, _translate("MainWindow", "YoloV4-FB-512"))
        self.comboBox.setItemText(3, _translate("MainWindow", "YoloV4-CB-512"))
        self.comboBox.setItemText(4, _translate("MainWindow", "YoloV4-FB-640"))
        self.comboBox.setItemText(5, _translate("MainWindow", "YoloV4-CB-640"))

        self.comboBox.setItemText(6, _translate("MainWindow", "YoloV5_M-FB-416"))
        self.comboBox.setItemText(7, _translate("MainWindow", "YoloV5_M-CB-416"))
        self.comboBox.setItemText(8, _translate("MainWindow", "YoloV5_M-FB-512"))
        self.comboBox.setItemText(9, _translate("MainWindow", "YoloV5_M-CB-512"))
        self.comboBox.setItemText(10, _translate("MainWindow", "YoloV5_M-FB-640"))
        self.comboBox.setItemText(11, _translate("MainWindow", "YoloV5_M-CB-640"))

        self.comboBox.setItemText(12, _translate("MainWindow", "YoloV5_L-FB-416"))
        self.comboBox.setItemText(13, _translate("MainWindow", "YoloV5_L-CB-416"))
        self.comboBox.setItemText(14, _translate("MainWindow", "YoloV5_L-FB-512"))
        self.comboBox.setItemText(15, _translate("MainWindow", "YoloV5_L-CB-512"))
        self.comboBox.setItemText(16, _translate("MainWindow", "YoloV5_L-FB-640"))
        self.comboBox.setItemText(17, _translate("MainWindow", "YoloV5_L-CB-640"))

        self.comboBox.setItemText(18, _translate("MainWindow", "YoloV5_X-FB-416"))
        self.comboBox.setItemText(19, _translate("MainWindow", "YoloV5_X-CB-416"))
        self.comboBox.setItemText(20, _translate("MainWindow", "YoloV5_X-FB-512"))
        self.comboBox.setItemText(21, _translate("MainWindow", "YoloV5_X-CB-512"))
        self.comboBox.setItemText(22, _translate("MainWindow", "YoloV5_X-FB-640"))
        self.comboBox.setItemText(23, _translate("MainWindow", "YoloV5_X-CB-640"))

        self.comboBox.setItemText(24, _translate("MainWindow", "YOLOR_P-FB-416"))
        self.comboBox.setItemText(25, _translate("MainWindow", "YOLOR_P-CB-416"))
        self.comboBox.setItemText(26, _translate("MainWindow", "YOLOR_P-FB-512"))
        self.comboBox.setItemText(27, _translate("MainWindow", "YOLOR_P-CB-512"))
        self.comboBox.setItemText(28, _translate("MainWindow", "YOLOR_P-FB-640"))
        self.comboBox.setItemText(29, _translate("MainWindow", "YOLOR_P-CB-640"))

        self.comboBox.setItemText(30, _translate("MainWindow", "YOLOR_W-FB-416"))
        self.comboBox.setItemText(31, _translate("MainWindow", "YOLOR_W-CB-416"))
        self.comboBox.setItemText(32, _translate("MainWindow", "YOLOR_W-FB-512"))
        self.comboBox.setItemText(33, _translate("MainWindow", "YOLOR_W-CB-512"))
        self.comboBox.setItemText(34, _translate("MainWindow", "YOLOR_W-FB-640"))
        self.comboBox.setItemText(35, _translate("MainWindow", "YOLOR_W-CB-640"))

        self.dosya_sec.setText(_translate("MainWindow", "Dosya Seç"))
        self.klasor_sec.setText(_translate("MainWindow", "Klasör Seç"))
        self.durdur.setText(_translate("MainWindow", "Durdur"))

import bitirme_rc